### ISSUE TITLE
Define slides

### ISSUE THREAD

**Issue by Codingba** [valnub/welcomescreen-mobile#1]
Hi, i am new in freamwork7, in which file i need put code
 var welcomescreen_slides = [
  {
    id: 'slide0',
    picture: '<div class="tutorialicon">♥</div>',
    text: 'Welcome to this tutorial. In the next steps we will guide you through a manual that will teach you how to use this app.'
  }.....
thanks

**Comment by ghost** [comment]
this goes in your my-app.js file
