### ISSUE TITLE
Images not visible on slides

### ISSUE THREAD

**Issue by John-Henrique** [valnub/welcomescreen-mobile#3]
When using IMG tag in 'picture' key images aren't display. Example:
```
var welcomescreen_slides = [
  {
    id: 'slide0',
    picture: '<img src="img/my-image.png">',
    text: 'Welcome to this tutorial. In the next steps we will guide you through a manual that will teach you how to use this app.'
  }
];
```

I try  `picture: '<div class="tutorialicon"><img src="img/my-image.png"></div>'` but not working too... 

@valnub any idea?

**Comment by valnub** [comment]
Any error in console or network tab ?

**Comment by John-Henrique** [comment]
No errors, just seems have a CSS or JavaScript hidding images. Using last version of Welcomescreen.
![wellcomescreen-erro](https://user-images.githubusercontent.com/332925/36854097-e81a66a0-1d4e-11e8-8941-169b18c5c3a6.png)

**Comment by valnub** [comment]
Do you have a link for debugging ?

**Comment by John-Henrique** [comment]
You can see here http://johnhenrique.com.br/apps/
You need delete localStorage key after show wellcomescreen to show again.

**Comment by valnub** [comment]
@John-Henrique The img path does not exist. Can you give the full path `http://...` to the image?

**Comment by John-Henrique** [comment]
Example to first image from wellcomescreen https://johnhenrique.com.br/apps/img/welcomescreen/if_notes_add_103660-b.png
(updated files from server)

**Comment by valnub** [comment]
If I open that link I see no image

**Comment by John-Henrique** [comment]
When you open this link you can see the image in welcomescreen? :frowning:  http://johnhenrique.com.br/apps/

**Comment by valnub** [comment]
No, and it makes total sense because there is no image on your server. You need to fix that.
This is not a F7 or plugin issue.

**Comment by John-Henrique** [comment]
I found the error, in HTML tag is typed wrong `scr` and not `src`. Thanks...
