### ISSUE TITLE
parallax not working

### ISSUE THREAD

**Issue by BananaAcid** [valnub/welcomescreen-mobile#4]
`parallax: `, `parallaxBackgroundImage: ` don't seem to do anything.

**Comment by valnub** [comment]
How did you use it? Example?

**Comment by BananaAcid** [comment]
test is here [https://myvoyagemap.com/x-ws-test](https://myvoyagemap.com/x-ws-test)

**Comment by BananaAcid** [comment]
Having compared the Framework7 plugin with the standalone version, I just realized, there was no parallax options - sorry, I thought it was broken, not missing.

I am currently preparing a patch to include the f7 plugin options and missing css.

edit: see pull request.
